---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-demo # EKS Cluster name
  region: us-east-1 # Region Code to place EKS Cluster
  version: "1.22"
  
availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

managedNodeGroups:
  - name: node-group # Name of node group in EKS Cluster
    instanceType: t2.micro # Instance type for node group
    desiredCapacity: 3 # The number of worker node in EKS Cluster
    ssh:
      enableSsm: true
